#define SELECT 1
#define CREATE 2
#define UPDATE 3
#define DROP 4
#define INSERT 5
#define DELETE 6
#define INTEGER 7
#define SEMICOLON 8
#define FROM 9
#define WHERE 10
#define IDENTIFIER 11
#define INTO 12
